---
- name: "Stat the existence of keyfile"
  stat:
    path: "files/{{ ec2_security_key_name }}.pub"
  register: ec2_security_keyfile

- debug: var=ec2_security_keyfile
  when: "{{ ec2_security_key_debug | default('false') }}"

- name: "Ensure key {{ ec2_security_key_name }} is {{ ec2_security_key_state }}"
  local_action:
    module: ec2_key
    name: "{{ ec2_security_key_name }}"
    region: "{{ ec2_security_key_region }}"
    key_material: "{{ item }}"
    state: "{{ ec2_security_key_state }}"
  with_file: "{{ ec2_security_keyfile.path }}"
  when:  "{{ ec2_security_keyfile.stat.isreg | default('false') }}"
  register: return_ec2_security_key

- debug: var=return_ec2_security_key
  when: "{{ ec2_security_key_debug | default('false') }}"
